---
deployment:
  tasks:
    - export DEPLOYPATH=/home/$USER/travelingtypes.com
    - cd $DEPLOYPATH/backend && /usr/local/bin/php /usr/local/bin/composer install --no-dev --optimize-autoloader --no-interaction || true
    - cd $DEPLOYPATH/backend && /usr/local/bin/php artisan config:cache || true
    - cd $DEPLOYPATH/backend && /usr/local/bin/php artisan route:cache || true
    - cd $DEPLOYPATH/backend && /usr/local/bin/php artisan view:cache || true
    - /bin/chmod -R 755 $DEPLOYPATH/backend/storage || true
    - /bin/chmod -R 755 $DEPLOYPATH/backend/bootstrap/cache || true

